version: "3"

services:
  launcher:
    build:
      context: .
    ports:
      - "${PUBLIC_PORT}:8080"
      - "${WS_PUBLIC_PORT}:8080"
    environment:
      - FLAG=${FLAG}
      - LAUNCHER_PORT=8080
      # - DISABLE_TICKET=true
    tmpfs:
      - /tmp
