version: "3"

services:
  launcher:
    build:
      context: .
    ports:
      - "${PUBLIC_PORT}:8080"
    environment:
      - FLAG=${FLAG}
      - LAUNCHER_PORT=8080
      # - DISABLE_TICKET=true
    deploy:
      resources:
        limits:
          memory: 500M
