services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 50M

  takjilshare:
    build: .
    restart: on-failure
    ports:
      - 11451:5000
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 50M
