services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  takjilshare:
    build: .
    restart: always
    ports:
      - 11451:5000
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
