version: '3.9'

services:
    ret2win2:
        build: .
        restart: always
        ports:
            - "19001:1470"
        deploy:
          resources:
            limits:
              cpus: "0.001"
              memory: 50M
