version: '3.8'

services:
  challenge:
    build: .
    container_name: tobtobitobtobtobitobtobtobitobtobtobali
    ports:
      - "8888:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 50M

