services:
  app:
    build: .
    ports:
      - 16787:8080
    environment:
      - FLAG=RAMADAN{open_redirection_on_youtube_is_really_handy}
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 50M
